/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.event.ActionListener;

/**
 *
 * @author gayj5385
 */
public class OpenScreenTest
        extends javax.swing.JFrame
{

    /**
     * Creates new form OpenScreenTest
     */
    public OpenScreenTest()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        openScreenBtnPanel = new javax.swing.JPanel();
        logOnBtn = new javax.swing.JButton();
        registerBtn = new javax.swing.JButton();
        guestReservationBtn = new javax.swing.JButton();
        adminViewBtn = new javax.swing.JButton();
        logOnPanel = new javax.swing.JPanel();
        lblUN = new javax.swing.JLabel();
        pwFieldUserPw = new javax.swing.JPasswordField();
        txtUsername = new javax.swing.JTextField();
        lblPW = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        registrationBtn = new javax.swing.JButton();
        registerPanel = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        txtUsername1 = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        registationBtn = new javax.swing.JButton();
        guestReserve = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblReserverEmail = new javax.swing.JLabel();
        lblReserverLoc = new javax.swing.JLabel();
        cbReserverLocations = new javax.swing.JComboBox<>();
        txtReserverEmail = new javax.swing.JTextField();
        txrtReserverName = new javax.swing.JTextField();
        lblReserverDate = new javax.swing.JLabel();
        FTxtDatePicked = new javax.swing.JFormattedTextField();
        reserveBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Open Screen");
        setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().setLayout(new java.awt.CardLayout());

        logOnBtn.setText("Log On");
        logOnBtn.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                logOnBtnMouseClicked(evt);
            }
        });

        registerBtn.setText("Register");

        guestReservationBtn.setText("Guest Reserve");

        adminViewBtn.setText("Admin View");

        javax.swing.GroupLayout openScreenBtnPanelLayout = new javax.swing.GroupLayout(openScreenBtnPanel);
        openScreenBtnPanel.setLayout(openScreenBtnPanelLayout);
        openScreenBtnPanelLayout.setHorizontalGroup(
            openScreenBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, openScreenBtnPanelLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(openScreenBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(openScreenBtnPanelLayout.createSequentialGroup()
                        .addComponent(logOnBtn)
                        .addGap(18, 18, 18)
                        .addComponent(guestReservationBtn)
                        .addGap(18, 18, 18)
                        .addComponent(adminViewBtn))
                    .addComponent(registerBtn))
                .addGap(19, 19, 19))
        );
        openScreenBtnPanelLayout.setVerticalGroup(
            openScreenBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(openScreenBtnPanelLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(openScreenBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logOnBtn)
                    .addComponent(guestReservationBtn)
                    .addComponent(adminViewBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registerBtn)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        getContentPane().add(openScreenBtnPanel, "card2");

        lblUN.setText("Username");

        txtUsername.setToolTipText("Username");

        lblPW.setText("Password");

        loginBtn.setText("Log in");

        registrationBtn.setText("Register");

        javax.swing.GroupLayout logOnPanelLayout = new javax.swing.GroupLayout(logOnPanel);
        logOnPanel.setLayout(logOnPanelLayout);
        logOnPanelLayout.setHorizontalGroup(
            logOnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logOnPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(logOnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(logOnPanelLayout.createSequentialGroup()
                        .addGroup(logOnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUN)
                            .addComponent(lblPW))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(logOnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pwFieldUserPw)
                            .addComponent(txtUsername)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logOnPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                        .addComponent(registrationBtn)
                        .addGap(18, 18, 18)
                        .addComponent(loginBtn)))
                .addGap(29, 29, 29))
        );
        logOnPanelLayout.setVerticalGroup(
            logOnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logOnPanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(logOnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUN)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(logOnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pwFieldUserPw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPW))
                .addGap(18, 18, 18)
                .addGroup(logOnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginBtn)
                    .addComponent(registrationBtn))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        getContentPane().add(logOnPanel, "card3");

        lblUsername.setText("Username");

        lblPassword.setText("Password");

        lblEmail.setText("Email");

        lblPhone.setText("Phone");

        txtUsername1.setToolTipText("username cannot contain spaces");

        txtPassword.setToolTipText("Password must contain:\n* 1 uppercase\n* 1 lowercase\n* 1 symbol\n* 1 number\n* minimum 8 characters\n* maximum 64 characters");

        txtEmail.setToolTipText("something@email.com");

        txtPhone.setToolTipText("phone number format should look as follows 555-123-4567");

        registationBtn.setText("Register");

        javax.swing.GroupLayout registerPanelLayout = new javax.swing.GroupLayout(registerPanel);
        registerPanel.setLayout(registerPanelLayout);
        registerPanelLayout.setHorizontalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPanelLayout.createSequentialGroup()
                        .addGap(0, 273, Short.MAX_VALUE)
                        .addComponent(registationBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPanelLayout.createSequentialGroup()
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPhone)
                            .addComponent(lblEmail)
                            .addComponent(lblUsername)
                            .addComponent(lblPassword))
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(registerPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))
                            .addGroup(registerPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))
                            .addGroup(registerPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPassword)
                                    .addComponent(txtUsername1))))
                        .addGap(41, 41, 41))))
        );
        registerPanelLayout.setVerticalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPanelLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhone)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(registationBtn)
                .addGap(18, 18, 18))
        );

        getContentPane().add(registerPanel, "card4");

        lblName.setText("Name");

        lblReserverEmail.setText("Email");

        lblReserverLoc.setText("Location");

        cbReserverLocations.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtReserverEmail.setText("jTextField1");

        txrtReserverName.setToolTipText("");

        lblReserverDate.setText("Date");

        FTxtDatePicked.setToolTipText("01/01/2017");

        reserveBtn.setText("Reserve");

        javax.swing.GroupLayout guestReserveLayout = new javax.swing.GroupLayout(guestReserve);
        guestReserve.setLayout(guestReserveLayout);
        guestReserveLayout.setHorizontalGroup(
            guestReserveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guestReserveLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(guestReserveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblReserverLoc)
                    .addComponent(lblReserverEmail)
                    .addComponent(lblName)
                    .addComponent(lblReserverDate))
                .addGap(41, 41, 41)
                .addGroup(guestReserveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbReserverLocations, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtReserverEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(txrtReserverName)
                    .addComponent(FTxtDatePicked))
                .addContainerGap(93, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, guestReserveLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(reserveBtn)
                .addGap(51, 51, 51))
        );
        guestReserveLayout.setVerticalGroup(
            guestReserveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guestReserveLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(guestReserveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txrtReserverName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(guestReserveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReserverEmail)
                    .addComponent(txtReserverEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(guestReserveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReserverLoc)
                    .addComponent(cbReserverLocations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(guestReserveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReserverDate)
                    .addComponent(FTxtDatePicked, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(reserveBtn)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        getContentPane().add(guestReserve, "card5");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logOnBtnMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_logOnBtnMouseClicked
    {//GEN-HEADEREND:event_logOnBtnMouseClicked
        
    }//GEN-LAST:event_logOnBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info
                    : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(OpenScreenTest.class.getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(OpenScreenTest.class.getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(OpenScreenTest.class.getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(OpenScreenTest.class.getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new OpenScreenTest().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField FTxtDatePicked;
    private javax.swing.JButton adminViewBtn;
    private javax.swing.JComboBox<String> cbReserverLocations;
    private javax.swing.JButton guestReservationBtn;
    private javax.swing.JPanel guestReserve;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPW;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblReserverDate;
    private javax.swing.JLabel lblReserverEmail;
    private javax.swing.JLabel lblReserverLoc;
    private javax.swing.JLabel lblUN;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JButton logOnBtn;
    private javax.swing.JPanel logOnPanel;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPanel openScreenBtnPanel;
    private javax.swing.JPasswordField pwFieldUserPw;
    private javax.swing.JButton registationBtn;
    private javax.swing.JButton registerBtn;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JButton registrationBtn;
    private javax.swing.JButton reserveBtn;
    private javax.swing.JTextField txrtReserverName;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtReserverEmail;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtUsername1;
    // End of variables declaration//GEN-END:variables
}
