/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.CardLayout;
import java.math.BigDecimal;
import java.util.GregorianCalendar;
import javax.swing.*;
/**
 *
 * @author gayj5385
 */
public class OpenScreenTest
        extends javax.swing.JFrame
{

    /**
     * Creates new form OpenScreenTest
     */
    public OpenScreenTest()
    {
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        Screens = new javax.swing.JPanel();
        openScreenBtnPanel = new javax.swing.JPanel();
        logOnBtn = new javax.swing.JButton();
        registerBtn = new javax.swing.JButton();
        guestReservationBtn = new javax.swing.JButton();
        adminViewBtn = new javax.swing.JButton();
        logOnPanel = new javax.swing.JPanel();
        lblUN = new javax.swing.JLabel();
        pwFieldUserPw = new javax.swing.JPasswordField();
        txtUsername = new javax.swing.JTextField();
        lblPW = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        registrationBtn = new javax.swing.JButton();
        registerPanel = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        txtUsername1 = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        registationBtn = new javax.swing.JButton();
        guestReserve = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblReserverEmail = new javax.swing.JLabel();
        lblReserverLoc = new javax.swing.JLabel();
        cbReserverLocations = new javax.swing.JComboBox<>();
        txtReserverEmail = new javax.swing.JTextField();
        txrtReserverName = new javax.swing.JTextField();
        lblReserverDate = new javax.swing.JLabel();
        FTxtDatePicked = new javax.swing.JFormattedTextField();
        reserveBtn = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        timelist = new javax.swing.JList<>();
        lblTimeDisplay = new javax.swing.JLabel();
        lblReserveType = new javax.swing.JLabel();
        txtReserveType = new javax.swing.JTextField();
        adminView = new javax.swing.JTabbedPane();
        reservationsAvailablePane = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        capdisplay = new javax.swing.JLabel();
        capacity = new javax.swing.JLabel();
        costDisplay = new javax.swing.JLabel();
        searchLocations = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        modifyLocBtn = new javax.swing.JButton();
        costAmount = new javax.swing.JLabel();
        adminExit = new javax.swing.JButton();
        reservationMangerPane = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        reservationList = new javax.swing.JList<>();
        reservationInformation = new javax.swing.JPanel();
        locDisplay = new javax.swing.JLabel();
        dateDisplay = new javax.swing.JLabel();
        timeDisplay = new javax.swing.JLabel();
        costDisplauy = new javax.swing.JLabel();
        capDisplay = new javax.swing.JLabel();
        capacity1 = new javax.swing.JLabel();
        costNum = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        locName = new javax.swing.JLabel();
        timeSlot = new javax.swing.JLabel();
        eventTypeDisplay = new javax.swing.JLabel();
        capacity2 = new javax.swing.JLabel();
        reserverContactInfo = new javax.swing.JPanel();
        nameDisplay = new javax.swing.JLabel();
        emailDisplauy = new javax.swing.JLabel();
        phoneDisplay = new javax.swing.JLabel();
        idDisplay = new javax.swing.JLabel();
        phoneString = new javax.swing.JLabel();
        emailString = new javax.swing.JLabel();
        idNum2 = new javax.swing.JLabel();
        nameString = new javax.swing.JLabel();
        reserveAdminSearch = new javax.swing.JTextField();
        reserveSearchBtn = new javax.swing.JButton();
        reserveExitBtn = new javax.swing.JButton();
        cancelReserveBtn = new javax.swing.JButton();
        contactReserverBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Open Screen");
        setBackground(new java.awt.Color(102, 102, 102));

        Screens.setLayout(new java.awt.CardLayout());

        logOnBtn.setText("Log On");
        logOnBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                logOnBtnActionPerformed(evt);
            }
        });

        registerBtn.setText("Register");
        registerBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                registerBtnActionPerformed(evt);
            }
        });

        guestReservationBtn.setText("Guest Reserve");
        guestReservationBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                reserveClick(evt);
            }
        });

        adminViewBtn.setText("Admin View");
        adminViewBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                adminViewBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout openScreenBtnPanelLayout = new javax.swing.GroupLayout(openScreenBtnPanel);
        openScreenBtnPanel.setLayout(openScreenBtnPanelLayout);
        openScreenBtnPanelLayout.setHorizontalGroup(
            openScreenBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(openScreenBtnPanelLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(logOnBtn)
                .addGap(29, 29, 29)
                .addComponent(registerBtn)
                .addGap(18, 18, 18)
                .addComponent(guestReservationBtn)
                .addGap(18, 18, 18)
                .addComponent(adminViewBtn)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        openScreenBtnPanelLayout.setVerticalGroup(
            openScreenBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(openScreenBtnPanelLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(openScreenBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logOnBtn)
                    .addComponent(guestReservationBtn)
                    .addComponent(adminViewBtn)
                    .addComponent(registerBtn))
                .addContainerGap(210, Short.MAX_VALUE))
        );

        Screens.add(openScreenBtnPanel, "openScreen");

        lblUN.setText("Username");

        txtUsername.setToolTipText("Username");

        lblPW.setText("Password");

        loginBtn.setText("Log in");
        loginBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                loginBtnActionPerformed(evt);
            }
        });

        registrationBtn.setText("Register");
        registrationBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                registrationBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout logOnPanelLayout = new javax.swing.GroupLayout(logOnPanel);
        logOnPanel.setLayout(logOnPanelLayout);
        logOnPanelLayout.setHorizontalGroup(
            logOnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logOnPanelLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(logOnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(logOnPanelLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(registrationBtn)
                        .addGap(18, 18, 18)
                        .addComponent(loginBtn)
                        .addGap(259, 259, 259))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logOnPanelLayout.createSequentialGroup()
                        .addGroup(logOnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUN)
                            .addComponent(lblPW))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(logOnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pwFieldUserPw)
                            .addComponent(txtUsername))
                        .addGap(93, 93, 93))))
        );
        logOnPanelLayout.setVerticalGroup(
            logOnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logOnPanelLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(logOnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUN)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(logOnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pwFieldUserPw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPW))
                .addGap(18, 18, 18)
                .addGroup(logOnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginBtn)
                    .addComponent(registrationBtn))
                .addContainerGap(170, Short.MAX_VALUE))
        );

        Screens.add(logOnPanel, "logonScreen");

        lblUsername.setText("Username");

        lblPassword.setText("Password");

        lblEmail.setText("Email");

        lblPhone.setText("Phone");

        txtUsername1.setToolTipText("username cannot contain spaces");

        txtPassword.setToolTipText("Password must contain:\n* 1 uppercase\n* 1 lowercase\n* 1 symbol\n* 1 number\n* minimum 8 characters\n* maximum 64 characters");

        txtEmail.setToolTipText("something@email.com");

        txtPhone.setToolTipText("phone number format should look as follows 555-123-4567");

        registationBtn.setText("Register");
        registationBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                registationBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registerPanelLayout = new javax.swing.GroupLayout(registerPanel);
        registerPanel.setLayout(registerPanelLayout);
        registerPanelLayout.setHorizontalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(registationBtn)
                    .addGroup(registerPanelLayout.createSequentialGroup()
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPhone)
                            .addComponent(lblEmail)
                            .addComponent(lblUsername)
                            .addComponent(lblPassword))
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(registerPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtPassword)
                                        .addComponent(txtUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        registerPanelLayout.setVerticalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhone)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(registationBtn)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        Screens.add(registerPanel, "registerScreen");

        lblName.setText("Name");

        lblReserverEmail.setText("Email");

        lblReserverLoc.setText("Location");

        cbReserverLocations.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txrtReserverName.setToolTipText("");

        lblReserverDate.setText("Date");

        FTxtDatePicked.setToolTipText("01/01/2017");

        reserveBtn.setText("Reserve");
        reserveBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                reserveBtnActionPerformed(evt);
            }
        });

        timelist.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        timelist.setModel(new javax.swing.AbstractListModel<String>()
        {
            String[] strings = { "Time Start , Time End", "Time Start , Time End", "Time Start , Time End", "Time Start , Time End", "Time Start , Time End" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        timelist.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        timelist.setToolTipText("");
        jScrollPane4.setViewportView(timelist);

        lblTimeDisplay.setText("Time:");

        lblReserveType.setText("Type");

        javax.swing.GroupLayout guestReserveLayout = new javax.swing.GroupLayout(guestReserve);
        guestReserve.setLayout(guestReserveLayout);
        guestReserveLayout.setHorizontalGroup(
            guestReserveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guestReserveLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(guestReserveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblReserverLoc)
                    .addComponent(lblReserverEmail)
                    .addComponent(lblName)
                    .addComponent(lblReserverDate)
                    .addComponent(lblTimeDisplay)
                    .addComponent(lblReserveType))
                .addGap(41, 41, 41)
                .addGroup(guestReserveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4)
                    .addComponent(cbReserverLocations, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtReserverEmail)
                    .addComponent(txrtReserverName)
                    .addComponent(FTxtDatePicked, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(txtReserveType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(reserveBtn)
                .addGap(26, 26, 26))
        );
        guestReserveLayout.setVerticalGroup(
            guestReserveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, guestReserveLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(guestReserveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txrtReserverName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(guestReserveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReserverEmail)
                    .addComponent(txtReserverEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(guestReserveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReserverLoc)
                    .addComponent(cbReserverLocations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(guestReserveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReserverDate)
                    .addComponent(FTxtDatePicked, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(guestReserveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblReserveType)
                    .addComponent(txtReserveType, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(guestReserveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, guestReserveLayout.createSequentialGroup()
                        .addComponent(reserveBtn)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, guestReserveLayout.createSequentialGroup()
                        .addGroup(guestReserveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTimeDisplay)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        Screens.add(guestReserve, "guestReserveScreen");

        adminView.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        adminView.setName(""); // NOI18N

        jTextField1.setToolTipText("");

        jComboBox1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jList1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>()
        {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTextArea1);

        capdisplay.setText("Capacity");

        capacity.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        capacity.setMaximumSize(new java.awt.Dimension(0, 0));

        costDisplay.setText("Cost");

        searchLocations.setMnemonic('s');
        searchLocations.setText("Search");
        searchLocations.setToolTipText("");
        searchLocations.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                searchLocationsActionPerformed(evt);
            }
        });

        addBtn.setMnemonic('a');
        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                addBtnActionPerformed(evt);
            }
        });

        removeBtn.setMnemonic('r');
        removeBtn.setText("Remove");
        removeBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                removeBtnActionPerformed(evt);
            }
        });

        modifyLocBtn.setMnemonic('m');
        modifyLocBtn.setText("Modify Location");
        modifyLocBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                modifyLocBtnActionPerformed(evt);
            }
        });

        costAmount.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        costAmount.setMaximumSize(new java.awt.Dimension(0, 0));

        adminExit.setMnemonic('x');
        adminExit.setText("Exit");
        adminExit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                adminExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout reservationsAvailablePaneLayout = new javax.swing.GroupLayout(reservationsAvailablePane);
        reservationsAvailablePane.setLayout(reservationsAvailablePaneLayout);
        reservationsAvailablePaneLayout.setHorizontalGroup(
            reservationsAvailablePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reservationsAvailablePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reservationsAvailablePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reservationsAvailablePaneLayout.createSequentialGroup()
                        .addGroup(reservationsAvailablePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jComboBox1, 0, 122, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(reservationsAvailablePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(reservationsAvailablePaneLayout.createSequentialGroup()
                                .addGroup(reservationsAvailablePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(capdisplay)
                                    .addComponent(costDisplay))
                                .addGap(31, 31, 31)
                                .addGroup(reservationsAvailablePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(costAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(capacity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(reservationsAvailablePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reservationsAvailablePaneLayout.createSequentialGroup()
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap())
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reservationsAvailablePaneLayout.createSequentialGroup()
                                        .addGroup(reservationsAvailablePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(adminExit)
                                            .addComponent(searchLocations, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(20, 20, 20))))
                            .addGroup(reservationsAvailablePaneLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 193, Short.MAX_VALUE))))
                    .addGroup(reservationsAvailablePaneLayout.createSequentialGroup()
                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(removeBtn)
                        .addGap(12, 12, 12)
                        .addComponent(modifyLocBtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        reservationsAvailablePaneLayout.setVerticalGroup(
            reservationsAvailablePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reservationsAvailablePaneLayout.createSequentialGroup()
                .addGroup(reservationsAvailablePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reservationsAvailablePaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(reservationsAvailablePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(reservationsAvailablePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(capdisplay))
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(capacity, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(reservationsAvailablePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(reservationsAvailablePaneLayout.createSequentialGroup()
                                .addGroup(reservationsAvailablePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(searchLocations, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(costAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(costDisplay))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2))
                            .addGroup(reservationsAvailablePaneLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 60, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(reservationsAvailablePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(modifyLocBtn)
                            .addComponent(removeBtn)
                            .addComponent(addBtn)))
                    .addGroup(javax.swing.GroupLayout.Alignment.CENTER, reservationsAvailablePaneLayout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(adminExit)))
                .addGap(13, 13, 13))
        );

        adminView.addTab("Reservations Available", reservationsAvailablePane);
        reservationsAvailablePane.getAccessibleContext().setAccessibleName("");
        reservationsAvailablePane.getAccessibleContext().setAccessibleDescription("");

        reservationList.setModel(new javax.swing.AbstractListModel<String>()
        {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(reservationList);

        locDisplay.setText("Location:");

        dateDisplay.setText("Date:");

        timeDisplay.setText("Time");

        costDisplauy.setText("Cost");

        capDisplay.setText("Capacity");

        capacity1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        capacity1.setMaximumSize(new java.awt.Dimension(0, 0));

        costNum.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        costNum.setMaximumSize(new java.awt.Dimension(0, 0));

        date.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        date.setMaximumSize(new java.awt.Dimension(0, 0));

        locName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        locName.setMaximumSize(new java.awt.Dimension(0, 0));

        timeSlot.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        timeSlot.setMaximumSize(new java.awt.Dimension(0, 0));

        eventTypeDisplay.setText("Type");

        capacity2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        capacity2.setMaximumSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout reservationInformationLayout = new javax.swing.GroupLayout(reservationInformation);
        reservationInformation.setLayout(reservationInformationLayout);
        reservationInformationLayout.setHorizontalGroup(
            reservationInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reservationInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reservationInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(locDisplay)
                    .addComponent(dateDisplay)
                    .addComponent(capDisplay)
                    .addComponent(costDisplauy)
                    .addComponent(timeDisplay)
                    .addComponent(eventTypeDisplay))
                .addGap(18, 18, 18)
                .addGroup(reservationInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(capacity1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(capacity2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeSlot, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(locName, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(costNum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        reservationInformationLayout.setVerticalGroup(
            reservationInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reservationInformationLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(reservationInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(locDisplay)
                    .addComponent(locName, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(reservationInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reservationInformationLayout.createSequentialGroup()
                        .addComponent(dateDisplay)
                        .addGap(13, 13, 13)
                        .addComponent(timeDisplay))
                    .addGroup(reservationInformationLayout.createSequentialGroup()
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(timeSlot, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(reservationInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(costDisplauy)
                    .addComponent(capacity2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reservationInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(capacity1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(capDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reservationInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eventTypeDisplay)
                    .addComponent(costNum, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        nameDisplay.setText("Name:");

        emailDisplauy.setText("Email");

        phoneDisplay.setText("Phone");

        idDisplay.setText("ID");

        phoneString.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        phoneString.setMaximumSize(new java.awt.Dimension(0, 0));

        emailString.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        emailString.setMaximumSize(new java.awt.Dimension(0, 0));

        idNum2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        idNum2.setMaximumSize(new java.awt.Dimension(0, 0));

        nameString.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nameString.setMaximumSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout reserverContactInfoLayout = new javax.swing.GroupLayout(reserverContactInfo);
        reserverContactInfo.setLayout(reserverContactInfoLayout);
        reserverContactInfoLayout.setHorizontalGroup(
            reserverContactInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reserverContactInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reserverContactInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reserverContactInfoLayout.createSequentialGroup()
                        .addComponent(idDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reserverContactInfoLayout.createSequentialGroup()
                        .addGroup(reserverContactInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(phoneDisplay)
                            .addComponent(emailDisplauy)
                            .addComponent(nameDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 6)))
                .addGroup(reserverContactInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idNum2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameString, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailString, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneString, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        reserverContactInfoLayout.setVerticalGroup(
            reserverContactInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reserverContactInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reserverContactInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idNum2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(reserverContactInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameString, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(reserverContactInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailDisplauy, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailString, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(reserverContactInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phoneDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneString, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );

        reserveSearchBtn.setMnemonic('s');
        reserveSearchBtn.setText("Search");

        reserveExitBtn.setMnemonic('x');
        reserveExitBtn.setText("Exit");
        reserveExitBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                reserveExitBtnActionPerformed(evt);
            }
        });

        cancelReserveBtn.setMnemonic('c');
        cancelReserveBtn.setText("Cancel Reserve");
        cancelReserveBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cancelReserveBtnActionPerformed(evt);
            }
        });

        contactReserverBtn.setMnemonic('o');
        contactReserverBtn.setText("Contact");
        contactReserverBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                contactReserverBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout reservationMangerPaneLayout = new javax.swing.GroupLayout(reservationMangerPane);
        reservationMangerPane.setLayout(reservationMangerPaneLayout);
        reservationMangerPaneLayout.setHorizontalGroup(
            reservationMangerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reservationMangerPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reservationMangerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reservationMangerPaneLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(reserveAdminSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(reservationMangerPaneLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(reservationMangerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cancelReserveBtn)
                            .addComponent(reservationInformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(reservationMangerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(reservationMangerPaneLayout.createSequentialGroup()
                                .addComponent(contactReserverBtn)
                                .addGap(53, 53, 53)
                                .addComponent(reserveExitBtn))
                            .addGroup(reservationMangerPaneLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(reserverContactInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(reserveSearchBtn)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        reservationMangerPaneLayout.setVerticalGroup(
            reservationMangerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reservationMangerPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reserveAdminSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reservationMangerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reservationMangerPaneLayout.createSequentialGroup()
                        .addGroup(reservationMangerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(reservationMangerPaneLayout.createSequentialGroup()
                                .addGap(0, 45, Short.MAX_VALUE)
                                .addGroup(reservationMangerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane3)
                                    .addComponent(reserverContactInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(reservationMangerPaneLayout.createSequentialGroup()
                                .addComponent(reservationInformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(reservationMangerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cancelReserveBtn)
                            .addComponent(contactReserverBtn))
                        .addGap(33, 33, 33))
                    .addGroup(reservationMangerPaneLayout.createSequentialGroup()
                        .addComponent(reserveSearchBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(reserveExitBtn)
                        .addContainerGap())))
        );

        adminView.addTab("Manage Reservations", reservationMangerPane);

        Screens.add(adminView, "adminViewScreen");
        adminView.getAccessibleContext().setAccessibleName("Reservations available");

        getContentPane().add(Screens, java.awt.BorderLayout.CENTER);

        getAccessibleContext().setAccessibleName("EventMnger");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reserveClick(java.awt.event.ActionEvent evt)//GEN-FIRST:event_reserveClick
    {//GEN-HEADEREND:event_reserveClick
        
        CardLayout screen = (CardLayout)(Screens.getLayout());
        screen.show(Screens,"guestReserveScreen");
        
    }//GEN-LAST:event_reserveClick

    private void reserveBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_reserveBtnActionPerformed
    {//GEN-HEADEREND:event_reserveBtnActionPerformed
//        JOptionPane.showMessageDialog(null, "You have sent a reservation", "Made Reservation",
//                JOptionPane.OK_OPTION);
        String fName, lName,e,p, tempa;
         tempa = txrtReserverName.toString();
         String[] parts = tempa.split(" ");
         fName = parts[0];
         lName = parts[1];
         e = txtReserverEmail.toString();
         p = txtPhone.toString();
      
        Data.ContactInfo ConInfo = new Data.ContactInfo(fName, lName, e, p);
        Data.Reserver r = new Data.Reserver(ConInfo);
        
        tempa = txtReserveType.toString();
        
        Data.ReservableLocation loc = new Data.ReservableLocation(cbReserverLocations.toString(), ALLBITS);
        //Data.Reservation reservation = new Data.Reservation(loc, loc.indexOfTimeframe(timeframe), SOMEBITS, tempa);
        //need to get it to load the list with timeframes first and be able to pull it to this object.
        
        CardLayout screen = (CardLayout)(Screens.getLayout());
        screen.show(Screens,"openScreen");
    }//GEN-LAST:event_reserveBtnActionPerformed

    private void logOnBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_logOnBtnActionPerformed
    {//GEN-HEADEREND:event_logOnBtnActionPerformed
         CardLayout screen = (CardLayout)(Screens.getLayout());
        screen.show(Screens,"logonScreen");
    }//GEN-LAST:event_logOnBtnActionPerformed

    private void registrationBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_registrationBtnActionPerformed
    {//GEN-HEADEREND:event_registrationBtnActionPerformed
         CardLayout screen = (CardLayout)(Screens.getLayout());
        screen.show(Screens,"registerScreen");
    }//GEN-LAST:event_registrationBtnActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_loginBtnActionPerformed
    {//GEN-HEADEREND:event_loginBtnActionPerformed
        JOptionPane.showMessageDialog(null, "Logged in", "You have logged in",
                JOptionPane.OK_OPTION);
        
        
        CardLayout screen = (CardLayout)(Screens.getLayout());
        screen.show(Screens,"openScreen");
    }//GEN-LAST:event_loginBtnActionPerformed

    private void registationBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_registationBtnActionPerformed
    {//GEN-HEADEREND:event_registationBtnActionPerformed
        JOptionPane.showMessageDialog(null, "You have sent registered", "Made user",
                JOptionPane.OK_OPTION);
        CardLayout screen = (CardLayout)(Screens.getLayout());
        screen.show(Screens,"openScreen");
    }//GEN-LAST:event_registationBtnActionPerformed

    private void cancelReserveBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelReserveBtnActionPerformed
    {//GEN-HEADEREND:event_cancelReserveBtnActionPerformed
        JOptionPane.showMessageDialog(null, "You have cancled Reservation", "Cancel Reservation",
                JOptionPane.OK_OPTION);
    }//GEN-LAST:event_cancelReserveBtnActionPerformed

    private void adminViewBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_adminViewBtnActionPerformed
    {//GEN-HEADEREND:event_adminViewBtnActionPerformed
       CardLayout screen = (CardLayout)(Screens.getLayout());
        screen.show(Screens,"adminViewScreen");
    }//GEN-LAST:event_adminViewBtnActionPerformed

    private void contactReserverBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_contactReserverBtnActionPerformed
    {//GEN-HEADEREND:event_contactReserverBtnActionPerformed
        JOptionPane.showMessageDialog(null, "You have emailed your contact", "Email reserver",
                JOptionPane.OK_OPTION);
    }//GEN-LAST:event_contactReserverBtnActionPerformed

    private void reserveExitBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_reserveExitBtnActionPerformed
    {//GEN-HEADEREND:event_reserveExitBtnActionPerformed
         CardLayout screen = (CardLayout)(Screens.getLayout());
        screen.show(Screens,"logonScreen");
    }//GEN-LAST:event_reserveExitBtnActionPerformed

    private void adminExitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_adminExitActionPerformed
    {//GEN-HEADEREND:event_adminExitActionPerformed
         CardLayout screen = (CardLayout)(Screens.getLayout());
        screen.show(Screens,"logonScreen");
    }//GEN-LAST:event_adminExitActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addBtnActionPerformed
    {//GEN-HEADEREND:event_addBtnActionPerformed
         JOptionPane.showMessageDialog(null, "You have added the location info", "Location Add",
                JOptionPane.OK_OPTION);
    }//GEN-LAST:event_addBtnActionPerformed

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_removeBtnActionPerformed
    {//GEN-HEADEREND:event_removeBtnActionPerformed
         JOptionPane.showMessageDialog(null, "You have removed the Time", "Location Time Remove",
                JOptionPane.OK_OPTION);
    }//GEN-LAST:event_removeBtnActionPerformed

    private void modifyLocBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_modifyLocBtnActionPerformed
    {//GEN-HEADEREND:event_modifyLocBtnActionPerformed
         JOptionPane.showMessageDialog(null, "You have Modified the location", "Location Modify",
                JOptionPane.OK_OPTION);
    }//GEN-LAST:event_modifyLocBtnActionPerformed

    private void searchLocationsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_searchLocationsActionPerformed
    {//GEN-HEADEREND:event_searchLocationsActionPerformed
         JOptionPane.showMessageDialog(null, "Your search is displayed", "Search Results",
                JOptionPane.OK_OPTION);
    }//GEN-LAST:event_searchLocationsActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_registerBtnActionPerformed
    {//GEN-HEADEREND:event_registerBtnActionPerformed
        CardLayout screen = (CardLayout)(Screens.getLayout());
        screen.show(Screens,"registerScreen");
        
    }//GEN-LAST:event_registerBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info
                    : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(OpenScreenTest.class.getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(OpenScreenTest.class.getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(OpenScreenTest.class.getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(OpenScreenTest.class.getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new OpenScreenTest().setVisible(true);
            }
        });
        
        
    }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField FTxtDatePicked;
    private javax.swing.JPanel Screens;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton adminExit;
    private javax.swing.JTabbedPane adminView;
    private javax.swing.JButton adminViewBtn;
    private javax.swing.JButton cancelReserveBtn;
    private javax.swing.JLabel capDisplay;
    private javax.swing.JLabel capacity;
    private javax.swing.JLabel capacity1;
    private javax.swing.JLabel capacity2;
    private javax.swing.JLabel capdisplay;
    private javax.swing.JComboBox<String> cbReserverLocations;
    private javax.swing.JButton contactReserverBtn;
    private javax.swing.JLabel costAmount;
    private javax.swing.JLabel costDisplauy;
    private javax.swing.JLabel costDisplay;
    private javax.swing.JLabel costNum;
    private javax.swing.JLabel date;
    private javax.swing.JLabel dateDisplay;
    private javax.swing.JLabel emailDisplauy;
    private javax.swing.JLabel emailString;
    private javax.swing.JLabel eventTypeDisplay;
    private javax.swing.JButton guestReservationBtn;
    private javax.swing.JPanel guestReserve;
    private javax.swing.JLabel idDisplay;
    private javax.swing.JLabel idNum2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPW;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblReserveType;
    private javax.swing.JLabel lblReserverDate;
    private javax.swing.JLabel lblReserverEmail;
    private javax.swing.JLabel lblReserverLoc;
    private javax.swing.JLabel lblTimeDisplay;
    private javax.swing.JLabel lblUN;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel locDisplay;
    private javax.swing.JLabel locName;
    private javax.swing.JButton logOnBtn;
    private javax.swing.JPanel logOnPanel;
    private javax.swing.JButton loginBtn;
    private javax.swing.JButton modifyLocBtn;
    private javax.swing.JLabel nameDisplay;
    private javax.swing.JLabel nameString;
    private javax.swing.JPanel openScreenBtnPanel;
    private javax.swing.JLabel phoneDisplay;
    private javax.swing.JLabel phoneString;
    private javax.swing.JPasswordField pwFieldUserPw;
    private javax.swing.JButton registationBtn;
    private javax.swing.JButton registerBtn;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JButton registrationBtn;
    private javax.swing.JButton removeBtn;
    private javax.swing.JPanel reservationInformation;
    private javax.swing.JList<String> reservationList;
    private javax.swing.JPanel reservationMangerPane;
    private javax.swing.JPanel reservationsAvailablePane;
    private javax.swing.JTextField reserveAdminSearch;
    private javax.swing.JButton reserveBtn;
    private javax.swing.JButton reserveExitBtn;
    private javax.swing.JButton reserveSearchBtn;
    private javax.swing.JPanel reserverContactInfo;
    private javax.swing.JButton searchLocations;
    private javax.swing.JLabel timeDisplay;
    private javax.swing.JLabel timeSlot;
    private javax.swing.JList<String> timelist;
    private javax.swing.JTextField txrtReserverName;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtReserveType;
    private javax.swing.JTextField txtReserverEmail;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtUsername1;
    // End of variables declaration//GEN-END:variables
}
